language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sudhendudesai/docker-react -f Dockerfile.dev .

Script:
  - docker run -e CI=true sudhendudesai/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-099679246516"
    bucket_path: "docker-react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY