language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sudhendudesai/docker-react -f Dockerfile.dev .

Script:
  - docker run -e CI=true sudhendudesai/docker-react npm run test